name: Documentation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # CORRECTED: Use the official action to install Hatch
      - name: Install Hatch
        uses: pypa/hatch@install

      - name: Build documentation
        run: hatch run docs:build

      - name: Check links
        run: hatch run docs:linkcheck
