---
name: Documentation Validation and Maintenance

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'docs/**'
      - 'src/**'
      - 'scripts/**'
      - 'pyproject.toml'
      - 'uv.lock'
      - '.github/workflows/documentation.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'docs/**'
      - 'src/**'
      - 'scripts/**'
      - 'pyproject.toml'
      - 'uv.lock'
      - '.github/workflows/documentation.yml'
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      maintenance_type:
        description: 'Type of maintenance to run'
        required: true
        default: 'audit'
        type: choice
        options:
        - audit
        - report
        - full_validation
        - quarterly

jobs:
  validate-documentation:
    name: Validate Docs (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }} and uv
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        # This automatically installs and caches uv and its virtual environment
        cache: 'uv'

    - name: Install dependencies
      # 'uv sync' installs dependencies from pyproject.toml/uv.lock
      # '--extra all' ensures test/dev dependencies like pytest are included
      run: uv sync --extra all

    - name: Run comprehensive documentation tests
      run: uv run pytest tests/test_comprehensive_documentation.py -v --tb=short

    - name: Validate code examples, API references, and configs
      run: uv run python scripts/validate_docs.py --all --verbose

    - name: Generate documentation coverage report
      run: uv run python scripts/validate_docs.py --coverage --export docs_coverage_report.json

    - name: Generate complete validation report
      if: always()
      run: uv run python scripts/validate_docs.py --all --coverage --verbose --export docs_complete_report.json > docs_validation_report.txt 2>&1 || true

    - name: Upload validation artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: validation-artifacts-py${{ matrix.python-version }}
        path: |
          docs_validation_report.txt
          docs_coverage_report.json
          docs_complete_report.json
        retention-days: 7

  check-quality:
    name: Check Quality (Coverage & Links)
    runs-on: ubuntu-latest
    needs: validate-documentation

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python and uv
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: 'uv'

    - name: Install quality tools
      # Assuming 'interrogate' is part of your 'all' extra in pyproject.toml
      run: uv sync --extra all

    - name: Check docstring coverage
      # interrogate checks for docstring coverage. -v is verbose, --fail-under is your quality gate.
      run: uv run interrogate -v --fail-under 80 src/

    - name: Check for broken links
      uses: lycheeverse/lychee-action@v1
      with:
        args: --verbose --max-concurrency 10 "./**/*.md" "./**/*.html"

  automated-documentation-updates:
    name: Automated Documentation Updates
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [validate-documentation, check-quality]

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python and uv
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: 'uv'

    - name: Install dependencies
      run: uv sync --extra all

    - name: Generate all documentation
      run: |
        uv run python src/docs/api_generator.py --output docs/api/ --format markdown
        # Add your other documentation generation scripts here

    - name: Commit and push documentation updates
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        if ! git diff --quiet docs/; then
          git add docs/
          git commit -m "docs: automated documentation updates [skip ci]"
          git push
        else
          echo "No documentation changes to commit."
        fi

  run-maintenance-tasks:
    name: Run Maintenance Tasks
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    needs: [validate-documentation, check-quality]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python and uv
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: 'uv'

    - name: Install dependencies
      run: uv sync --extra all

    - name: Run Maintenance Audit
      run: uv run python scripts/documentation_maintenance.py --audit --export maintenance_audit.json

    - name: Create Maintenance Issue if Needed
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const fs = require('fs');
          const audit = JSON.parse(fs.readFileSync('maintenance_audit.json', 'utf8'));
          if (audit.maintenance_info.maintenance_status === 'critical') {
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Critical Documentation Maintenance Required',
              body: 'The scheduled maintenance audit has identified critical issues. Please review the attached audit artifact.',
              labels: ['documentation', 'maintenance', 'critical']
            });
          }

    - name: Upload maintenance artifacts
      uses: actions/upload-artifact@v4
      with:
        name: maintenance-artifacts
        path: |
          maintenance_audit.json
        retention-days: 30
